<?xml version="1.0" encoding="UTF-8"?>
<!--
  events.xsl — XSLT Stylesheet to transform events.xml into HTML
  
  XSLT (Extensible Stylesheet Language Transformations) is used to
  transform XML documents into other formats (HTML, plain text, another XML).
  
  How it works:
  1. The XSLT processor reads events.xml (source document).
  2. It applies the rules (templates) defined in this .xsl file.
  3. The output is an HTML page you can open in a browser.
  
  Key XSLT elements used:
  - <xsl:template match="/">    : root template (entry point)
  - <xsl:for-each select="..."> : loop over elements
  - <xsl:value-of select="..."> : output the text content of an element
  - <xsl:choose> / <xsl:when>  : conditional logic (like if-else)
  - <xsl:sort>                  : sort elements before rendering
  
  To run: open events.xml in a browser (most modern browsers apply XSLT
  automatically when the XML references a stylesheet via <?xml-stylesheet...?>)
  
  Or run with Java:
      See XsltDemo.java in the xml/ folder.
-->
<xsl:stylesheet version="1.0"
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

    <!-- Output HTML, not XML -->
    <xsl:output method="html" encoding="UTF-8" indent="yes"
                doctype-public="-//W3C//DTD HTML 4.01//EN"/>

    <!-- Root template — matches the document root -->
    <xsl:template match="/">
        <html>
        <head>
            <title>Seminar and Workshop Events</title>
            <style>
                body { font-family: 'Segoe UI', Arial, sans-serif; background: #f1f5f9; color: #1e293b; margin: 0; padding: 20px; }
                h1 { color: #2563eb; border-bottom: 2px solid #2563eb; padding-bottom: 8px; }
                table { border-collapse: collapse; width: 100%; background: white; border-radius: 8px; overflow: hidden; box-shadow: 0 1px 4px rgba(0,0,0,0.1); }
                th { background: #2563eb; color: white; padding: 12px 14px; text-align: left; font-size: 0.88rem; }
                td { padding: 10px 14px; border-bottom: 1px solid #e2e8f0; font-size: 0.9rem; }
                tr:nth-child(even) td { background: #f8fafc; }
                .badge { display: inline-block; padding: 2px 10px; border-radius: 20px; font-size: 0.78rem; font-weight: bold; }
                .seminar  { background: #dbeafe; color: #1e40af; }
                .workshop { background: #ede9fe; color: #5b21b6; }
                .info { background: #eff6ff; border-left: 4px solid #2563eb; padding: 12px 16px; margin-bottom: 16px; border-radius: 4px; }
            </style>
        </head>
        <body>
            <h1>&#127979; College Seminars and Workshops</h1>
            
            <div class="info">
                This page was generated by transforming <strong>events.xml</strong> 
                using the XSLT stylesheet <strong>events.xsl</strong>.
                Total events: <xsl:value-of select="count(events/event)"/>
            </div>

            <table>
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Title</th>
                        <th>Type</th>
                        <th>Department</th>
                        <th>Date</th>
                        <th>Time</th>
                        <th>Venue</th>
                        <th>Speaker</th>
                        <th>Seats</th>
                    </tr>
                </thead>
                <tbody>
                    <!-- Loop over each <event> element, sorted by date -->
                    <xsl:for-each select="events/event">
                        <xsl:sort select="date"/>
                        <tr>
                            <td><xsl:value-of select="@id"/></td>
                            <td><strong><xsl:value-of select="title"/></strong></td>
                            <td>
                                <!-- Conditional: apply different CSS class based on type -->
                                <xsl:choose>
                                    <xsl:when test="type = 'Seminar'">
                                        <span class="badge seminar"><xsl:value-of select="type"/></span>
                                    </xsl:when>
                                    <xsl:otherwise>
                                        <span class="badge workshop"><xsl:value-of select="type"/></span>
                                    </xsl:otherwise>
                                </xsl:choose>
                            </td>
                            <td><xsl:value-of select="department"/></td>
                            <td><xsl:value-of select="date"/></td>
                            <td><xsl:value-of select="time"/></td>
                            <td><xsl:value-of select="venue"/></td>
                            <td><xsl:value-of select="speaker"/></td>
                            <td><xsl:value-of select="seats"/></td>
                        </tr>
                    </xsl:for-each>
                </tbody>
            </table>
        </body>
        </html>
    </xsl:template>

</xsl:stylesheet>
