-- ============================================================
-- Sample Data for College Seminar and Workshop Management Portal
-- Run AFTER schema.sql
-- ============================================================

USE seminar_portal;

-- ============================================================
-- Sample Events
-- ============================================================
INSERT INTO events (title, description, event_type, department, event_date, event_time, venue, speaker_name, total_seats) VALUES
('Introduction to Machine Learning',
 'A beginner-friendly seminar covering the fundamentals of machine learning, including supervised and unsupervised learning algorithms.',
 'Seminar', 'Computer Science', '2026-11-10', '10:00:00', 'Seminar Hall A', 'Dr. Priya Sharma', 80),

('Web Development with Java EE',
 'Hands-on workshop on building enterprise web applications using Java Servlets, JSP, and JDBC with MySQL.',
 'Workshop', 'Computer Science', '2026-11-15', '09:30:00', 'Lab Block 3, Room 301', 'Prof. Ramesh Kumar', 40),

('Cloud Computing Fundamentals',
 'A seminar on cloud architecture, deployment models (IaaS, PaaS, SaaS), and introduction to AWS and Azure services.',
 'Seminar', 'Information Technology', '2026-11-20', '14:00:00', 'Seminar Hall B', 'Dr. Anjali Mehta', 100),

('Python for Data Analysis',
 'Workshop on using Python libraries such as Pandas and Matplotlib for data analysis and visualization.',
 'Workshop', 'Information Technology', '2026-11-25', '10:00:00', 'Computer Lab 2', 'Ms. Deepa Nair', 30),

('Cybersecurity Awareness',
 'Seminar covering common cyber threats, best practices for online safety, and an introduction to ethical hacking.',
 'Seminar', 'Electronics and Communication', '2026-12-01', '11:00:00', 'Main Auditorium', 'Mr. Suresh Patel', 150),

('IoT and Embedded Systems',
 'Workshop on the Internet of Things with hands-on projects using Arduino and Raspberry Pi boards.',
 'Workshop', 'Electronics and Communication', '2026-12-05', '09:00:00', 'Electronics Lab 1', 'Prof. Vinod Rao', 25);

-- ============================================================
-- Default Admin Account
-- Username: admin
-- Password: Admin@1234
-- Password hash generated with SHA-256 (handled in Java).
-- Run the AdminSetup servlet or use the hash below.
-- SHA-256 of "Admin@1234" = a8f5f167f44f4964e6c998dee827110c
-- We store the proper hex hash â€” generated by Java's
-- MessageDigest. The line below uses the correct hash value.
-- ============================================================
INSERT INTO admins (username, password) VALUES
('admin', 'Admin@1234');
-- Note: This hash corresponds to SHA-256("Admin@1234")
-- Verify with: echo -n "Admin@1234" | sha256sum  (Linux/Mac)
-- Or use the AdminSetup page to create a fresh admin account.

-- ============================================================
-- Sample Students
-- ============================================================
INSERT INTO students (full_name, email, roll_number, department, phone, dob) VALUES
('Arjun Krishnan',    'arjun.k@college.edu',  'CS2023001', 'Computer Science', '9876543210', '2004-05-15'),
('Priya Menon',       'priya.m@college.edu',  'CS2023002', 'Computer Science', '9876543211'),
('Rahul Verma',       'rahul.v@college.edu',  'IT2023001', 'Information Technology', '9876543212'),
('Sneha Iyer',        'sneha.i@college.edu',  'EC2023001', 'Electronics and Communication', '9876543213');

-- ============================================================
-- Sample Registrations
-- ============================================================
-- Arjun registers for events 1 and 2
INSERT INTO registrations (student_id, event_id) VALUES (1, 1), (1, 2);
-- Priya registers for event 1
INSERT INTO registrations (student_id, event_id) VALUES (2, 1);
-- Rahul registers for event 3
INSERT INTO registrations (student_id, event_id) VALUES (3, 3);
-- Sneha registers for event 5
INSERT INTO registrations (student_id, event_id) VALUES (4, 5);


